"""
Admin Safety Routes — for the Lovable admin portal (and venue managers/staff).

Surfaces live `safety_alerts` entries generated by `/api/safety/silent-alert`
so Luna ops and the assigned venue team can triage them in real time.

Access rules:
- `admin` / `super_admin` → can see & action **all** alerts.
- `venue_manager` / `venue_staff` / `staff` / `manager` → can see & action
  only alerts tied to their `venue_id` (or `assigned_venue_id`).
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime, timezone, timedelta
import uuid

from database import db
from utils.auth import get_current_user
from luna_venues_config import LUNA_VENUES


router = APIRouter(prefix="/admin/safety", tags=["admin-safety"])


ADMIN_ROLES = {"admin", "super_admin"}
VENUE_ROLES = {"venue_manager", "venue_staff", "staff", "manager"}
ALLOWED_ROLES = ADMIN_ROLES | VENUE_ROLES


async def _require_safety_admin(request: Request) -> dict:
    user = get_current_user(request.headers.get("authorization"))
    if not user:
        raise HTTPException(status_code=401, detail="Authentication required")
    # JWT payload does not include role — fetch the live record
    record = await db.users.find_one({"user_id": user["user_id"]}, {"_id": 0})
    if not record:
        raise HTTPException(status_code=401, detail="User not found")
    role = record.get("role")
    if role not in ALLOWED_ROLES:
        raise HTTPException(status_code=403, detail="Safety admin access required")
    return record


def _scope_filter(user: dict) -> dict:
    """Return a Mongo query fragment limiting visibility to the user's scope."""
    if user.get("role") in ADMIN_ROLES:
        return {}
    vid = user.get("venue_id") or user.get("assigned_venue_id")
    if not vid:
        # Venue role without a venue assignment — see nothing
        return {"venue_id": "__none__"}
    return {"venue_id": vid}


def _serialise(alert: dict) -> dict:
    out = dict(alert)
    out.pop("_id", None)
    created = out.get("created_at")
    if isinstance(created, datetime):
        out["created_at"] = (
            created.replace(tzinfo=timezone.utc) if created.tzinfo is None else created
        ).isoformat()
    for key in ("acknowledged_at", "resolved_at"):
        val = out.get(key)
        if isinstance(val, datetime):
            out[key] = (val.replace(tzinfo=timezone.utc) if val.tzinfo is None else val).isoformat()
    # Acknowledged_by timestamps
    ack_list = out.get("acknowledged_by") or []
    cleaned_ack: List[dict] = []
    for ack in ack_list:
        if isinstance(ack, dict):
            at = ack.get("at")
            if isinstance(at, datetime):
                ack["at"] = (at.replace(tzinfo=timezone.utc) if at.tzinfo is None else at).isoformat()
            cleaned_ack.append(ack)
    out["acknowledged_by"] = cleaned_ack
    return out


@router.get("/alerts")
async def list_safety_alerts(
    request: Request,
    status: Optional[str] = None,
    venue_id: Optional[str] = None,
    hours: int = 48,
    limit: int = 100,
):
    """List safety alerts for the admin/lovable portal.

    Query:
      - `status`: `active` (default) | `resolved` | `all`
      - `venue_id`: filter to one venue (admins only; venue roles are already scoped)
      - `hours`: lookback window (default 48h)
      - `limit`: max rows (default 100, capped at 500)
    """
    user = await _require_safety_admin(request)
    status_filter = (status or "active").lower()
    limit = max(1, min(limit, 500))

    query: dict = {}
    query.update(_scope_filter(user))

    if venue_id and user.get("role") in ADMIN_ROLES:
        query["venue_id"] = venue_id

    if status_filter == "active":
        query["resolved"] = False
    elif status_filter == "resolved":
        query["resolved"] = True
    # "all" → no filter

    if hours and hours > 0:
        since = datetime.now(timezone.utc) - timedelta(hours=hours)
        query["created_at"] = {"$gte": since}

    cursor = db.safety_alerts.find(query).sort("created_at", -1).limit(limit)
    alerts = await cursor.to_list(limit)

    # Enrich with user info (avatar, phone) for the dashboard card
    user_ids = list({a.get("user_id") for a in alerts if a.get("user_id")})
    users_by_id: dict = {}
    if user_ids:
        u_docs = await db.users.find(
            {"user_id": {"$in": user_ids}},
            {"_id": 0, "user_id": 1, "name": 1, "email": 1, "phone": 1, "picture": 1, "subscription_tier": 1, "tier": 1},
        ).to_list(len(user_ids))
        users_by_id = {u["user_id"]: u for u in u_docs}

    enriched: List[dict] = []
    for a in alerts:
        s = _serialise(a)
        u = users_by_id.get(s.get("user_id"), {})
        s["user"] = {
            "user_id": s.get("user_id"),
            "name": u.get("name") or s.get("user_name") or "Unknown",
            "email": u.get("email"),
            "phone": u.get("phone"),
            "picture": u.get("picture"),
            "tier": u.get("subscription_tier") or u.get("tier"),
        }
        enriched.append(s)

    # Counts for the header
    counts_query = {k: v for k, v in query.items() if k != "resolved"}
    active_count = await db.safety_alerts.count_documents({**counts_query, "resolved": False})
    total_window = await db.safety_alerts.count_documents(counts_query)

    return {
        "alerts": enriched,
        "counts": {"active": active_count, "total_in_window": total_window, "returned": len(enriched)},
        "viewer": {
            "user_id": user.get("user_id"),
            "role": user.get("role"),
            "scope_venue_id": None if user.get("role") in ADMIN_ROLES else (user.get("venue_id") or user.get("assigned_venue_id")),
        },
        "filters": {"status": status_filter, "venue_id": venue_id, "hours": hours, "limit": limit},
    }


@router.get("/alerts/{alert_id}")
async def get_safety_alert(request: Request, alert_id: str):
    user = await _require_safety_admin(request)
    alert = await db.safety_alerts.find_one({"id": alert_id})
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    # Scope check
    if user.get("role") not in ADMIN_ROLES:
        vid = user.get("venue_id") or user.get("assigned_venue_id")
        if alert.get("venue_id") != vid:
            raise HTTPException(status_code=403, detail="Not in your venue scope")
    s = _serialise(alert)
    u = await db.users.find_one(
        {"user_id": alert.get("user_id")},
        {"_id": 0, "user_id": 1, "name": 1, "email": 1, "phone": 1, "picture": 1, "subscription_tier": 1, "tier": 1},
    )
    s["user"] = u or {"user_id": alert.get("user_id"), "name": alert.get("user_name")}

    # Venue details for quick reference
    if alert.get("venue_id") and alert["venue_id"] in LUNA_VENUES:
        v = LUNA_VENUES[alert["venue_id"]]
        s["venue"] = {
            "id": alert["venue_id"],
            "name": v.get("name"),
            "address": v.get("address"),
            "phone": (v.get("contact") or {}).get("phone"),
        }
    return s


class NotePayload(BaseModel):
    note: Optional[str] = None


@router.post("/alerts/{alert_id}/acknowledge")
async def acknowledge_safety_alert(request: Request, alert_id: str, payload: NotePayload):
    user = await _require_safety_admin(request)
    alert = await db.safety_alerts.find_one({"id": alert_id})
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    if user.get("role") not in ADMIN_ROLES:
        vid = user.get("venue_id") or user.get("assigned_venue_id")
        if alert.get("venue_id") != vid:
            raise HTTPException(status_code=403, detail="Not in your venue scope")

    now = datetime.now(timezone.utc)
    ack_entry = {
        "user_id": user["user_id"],
        "name": user.get("name"),
        "role": user.get("role"),
        "note": payload.note,
        "at": now,
    }
    await db.safety_alerts.update_one(
        {"id": alert_id},
        {
            "$addToSet": {"acknowledged_by": ack_entry},
            "$set": {"last_acknowledged_at": now, "status": "acknowledged" if not alert.get("resolved") else alert.get("status")},
        },
    )
    return {"success": True, "acknowledged_by": ack_entry}


@router.post("/alerts/{alert_id}/resolve")
async def resolve_safety_alert(request: Request, alert_id: str, payload: NotePayload):
    user = await _require_safety_admin(request)
    alert = await db.safety_alerts.find_one({"id": alert_id})
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    if user.get("role") not in ADMIN_ROLES:
        vid = user.get("venue_id") or user.get("assigned_venue_id")
        if alert.get("venue_id") != vid:
            raise HTTPException(status_code=403, detail="Not in your venue scope")

    now = datetime.now(timezone.utc)
    await db.safety_alerts.update_one(
        {"id": alert_id},
        {
            "$set": {
                "resolved": True,
                "resolved_at": now,
                "resolved_by": {
                    "user_id": user["user_id"],
                    "name": user.get("name"),
                    "role": user.get("role"),
                    "note": payload.note,
                },
                "status": "resolved",
            }
        },
    )

    # Notify the original alert-raiser that ops closed the alert
    try:
        await db.notifications.insert_one({
            "id": str(uuid.uuid4())[:10],
            "user_id": alert.get("user_id"),
            "type": "safety_alert_resolved",
            "title": "✅ Safety alert closed",
            "message": (
                f"Luna ops marked your silent alert as resolved"
                + (f" — note: {payload.note}" if payload.note else "")
                + "."
            ),
            "data": {"alert_id": alert_id},
            "priority": "normal",
            "read": False,
            "created_at": now,
        })
    except Exception:
        pass

    return {"success": True, "resolved_at": now.isoformat()}


@router.get("/summary")
async def safety_summary(request: Request, hours: int = 24):
    """Quick dashboard summary: counts by status + by venue + last 5 active alerts."""
    user = await _require_safety_admin(request)
    since = datetime.now(timezone.utc) - timedelta(hours=max(1, hours))
    base = {"created_at": {"$gte": since}}
    base.update(_scope_filter(user))

    active = await db.safety_alerts.count_documents({**base, "resolved": False})
    resolved = await db.safety_alerts.count_documents({**base, "resolved": True})

    pipeline = [
        {"$match": base},
        {"$group": {"_id": "$venue_id", "count": {"$sum": 1}}},
        {"$sort": {"count": -1}},
    ]
    by_venue_raw = await db.safety_alerts.aggregate(pipeline).to_list(50)
    by_venue = [
        {
            "venue_id": r.get("_id"),
            "venue_name": (LUNA_VENUES.get(r.get("_id")) or {}).get("name") if r.get("_id") else None,
            "count": r.get("count", 0),
        }
        for r in by_venue_raw
    ]

    recent_cursor = db.safety_alerts.find({**base, "resolved": False}).sort("created_at", -1).limit(5)
    recent = [_serialise(a) for a in await recent_cursor.to_list(5)]

    return {
        "window_hours": hours,
        "counts": {"active": active, "resolved": resolved, "total": active + resolved},
        "by_venue": by_venue,
        "recent_active": recent,
    }
